### ISSUE TITLE
Prev 버튼은 Design이 안되어있음

### ISSUE THREAD

**Issue by kajebiii** [cubelover/CoSNU#29]
![image](https://user-images.githubusercontent.com/32012515/41223475-de07faf0-6da4-11e8-8c8d-94b64bf87a18.png)

Prev랑

현재 숫자가 아닌 숫자들도 이상함

**Comment by kajebiii** [comment]
![image](https://user-images.githubusercontent.com/32012515/41228486-7beb3a58-6db3-11e8-874d-4538fd1b921c.png)
여기서 클릭하면 select로 대충 뜨게 했는데 예쁘게해줘

**Comment by kajebiii** [comment]
![image](https://user-images.githubusercontent.com/32012515/41228531-a640914a-6db3-11e8-9484-120de89090a2.png)

http://localhost:3000/lecture/10132413/list 같이 이상한 링크에서 Home 버튼 만들었는데 예쁘게해져

Home 버튼 표시하는 곳 좀 많은데 잘 찾아서 고쳐주셈

**Comment by cubelover** [comment]
Home 버튼은 그대로 둬도 괜찮은 것 같음
