### ISSUE TITLE
http://localhost:8000/lecture/1/article/3/comment/ 에 title이 없어야할듯

### ISSUE THREAD

**Issue by kajebiii** [cubelover/CoSNU#8]
![image](https://user-images.githubusercontent.com/32012515/40619070-9e9f8e72-62ce-11e8-8fec-18e1b6ed9262.png)

**Comment by woqja125** [comment]
drf가 자동생성하는 form에서만 필요하고, 실제로는 안넘겨도 댓글이 써질것.
추후 여유있을때 수정.
